### ISSUE TITLE
Using generics instead of trait objects?

### ISSUE THREAD

**Issue by aepsil0n** [vorot/roots#1]
Hello!

First of all, nice job implementing all of these algorithms in Rust :)

Now on to my issue: I started using your library and noticed that it uses trait objects quite heavily for passing functions and convergencies. Now, given that a function has to be evaluated rather often during computation, it might be useful for performance reasons to switch to generics for this. Have you considered that? I wonder what the implications would be.

Also it might be more ergonomic for users, as it means you do not have to pass in references to closures and trait objects, but can just pass them by value. For functions, you still can use a reference, as they implement `Fn` transitively. So I'd argue it is strictly more general to do it like this. You may even implement `Convergency` on references to keep this change backwards-compatible.

I would be happy to provide a pull request along those lines.

**Comment by aepsil0n** [comment]
I just realized that an implementation of `Convergency` on `&'a mut T` as I suggested is not possible as it conflicts with the blanket implementation on `F: FloatType`. So for convergencies that would be a breaking change.

**Comment by aepsil0n** [comment]
Just experimented with this idea and ran the following benchmarks on my laptop:

*before*

```
test biquadratic_x4_min_1_x1000    ... bench:      26,735 ns/iter (+/- 732)
test brent_x2_min_1_x1000          ... bench:     244,216 ns/iter (+/- 4,848)
test brent_x4_min_1_x1000          ... bench:     296,916 ns/iter (+/- 7,115)
test newton_raphson_x2_min_1_x1000 ... bench:      78,860 ns/iter (+/- 1,388)
test newton_raphson_x4_min_1_x1000 ... bench:     137,060 ns/iter (+/- 3,647)
test quadratic_x2_min_1_x1000      ... bench:       1,200 ns/iter (+/- 38)
test quartic_x4_min_1_x1000        ... bench:      26,892 ns/iter (+/- 733)
test regula_falsi_x2_min_1_x1000   ... bench:     137,427 ns/iter (+/- 3,670)
test regula_falsi_x4_min_1_x1000   ... bench:     272,681 ns/iter (+/- 5,817)
test secant_x2_min_1_x1000         ... bench:     166,078 ns/iter (+/- 4,289)
test secant_x4_min_1_x1000         ... bench:      74,540 ns/iter (+/- 3,901)
```

*after*

```
test biquadratic_x4_min_1_x1000    ... bench:      26,595 ns/iter (+/- 523)
test brent_x2_min_1_x1000          ... bench:     219,205 ns/iter (+/- 6,639)
test brent_x4_min_1_x1000          ... bench:     263,179 ns/iter (+/- 11,066)
test newton_raphson_x2_min_1_x1000 ... bench:      72,669 ns/iter (+/- 2,261)
test newton_raphson_x4_min_1_x1000 ... bench:     118,033 ns/iter (+/- 2,855)
test quadratic_x2_min_1_x1000      ... bench:       1,330 ns/iter (+/- 28)
test quartic_x4_min_1_x1000        ... bench:      26,704 ns/iter (+/- 755)
test regula_falsi_x2_min_1_x1000   ... bench:     126,611 ns/iter (+/- 3,535)
test regula_falsi_x4_min_1_x1000   ... bench:     262,417 ns/iter (+/- 5,237)
test secant_x2_min_1_x1000         ... bench:     161,310 ns/iter (+/- 3,400)
test secant_x4_min_1_x1000         ... bench:      67,252 ns/iter (+/- 2,115)
```

So for those benchmarks affected by the change, namely the numerical algorithms, we see a 10-15% performance improvement.

**Comment by vorot** [comment]
Hi,

Thank you for your contribution. The performance improvement is definitely worth of a few more generics.
