### ISSUE TITLE
roots::numerical::SearchError is private

### ISSUE THREAD

**Issue by JP-Ellis** [vorot/roots#10]
The numerical algorithms return `SearchError` as part of the `Result`; however the crate does not expose `SearchError`.  As a result, I can call the numerical algorithm functions, but if I wish to pass the result to another function, I cannot actually implement a function with the return type `Result<f64, SearchError>`.

Let me know if  you would like a PR.

**Comment by vorot** [comment]
> 
> 
> The numerical algorithms return `SearchError` as part of the `Result`; however the crate does not expose `SearchError`. As a result, I can call the numerical algorithm functions, but if I wish to pass the result to another function, I cannot actually implement a function with the return type `Result<f64, SearchError>`.
> 
> Let me know if you would like a PR.

Hi, thank you for using this library. A PR that exposes `SearchError` is welcome, as well as the one with extending the info provided by it. Please include at least one test case for each extension.

**Comment by vorot** [comment]
One-line change

**Comment by blagovestb2c2** [comment]
Hey, it seems that the latest available 0.0.6 version still has SearchError private. Could we perhaps get a new release that makes this change officially available

**Comment by vorot** [comment]
v0.0.7 is published

пн, 14 июн. 2021 г. в 13:58, blagovestb2c2 ***@***.***>:
