### ISSUE TITLE
FeatureSuggestion: FnMut for closures

### ISSUE THREAD

**Issue by vron** [vorot/roots#20]
Hi,

I have found myself a few times using roots (nice crate! thx!) in situations where:

 - Each step of the iteration involves running agains a large structure
 - I can re-evaluate my target function by doing minor modificaitons to my large structure

However, since e..g roots::find_root_brent requires a Fn I cannot pass a closure which captures a &mut ref to my struct and modify it in each iteration - instead I have to clone it every time to get a Fn closure instead of FnMut.

Would it be a good idea to accept FnMut closures for all the root functions or am I missing something?

**Comment by vorot** [comment]
It looks like a good idea. A pull request for this feature can be merged on a short notice.

**Comment by vorot** [comment]
done, it was easy.
