### ISSUE TITLE
find_roots_eigen Not Working for Polynomial of Degree 4 or More 

### ISSUE THREAD

**Issue by sebedard13** [vorot/roots#25]
I was transforming a python code to rust, the python library numpy seems to only use eigen for their [roots function](https://numpy.org/doc/stable/reference/generated/numpy.roots.html). I wanted to use the same. In my test I want the roots x^5 -2.5x^4 +5.0x^3 -5.0x^2 +2.5x -0.5, so : 
```
roots::find_roots_eigen(vec![-2.5,5.0,-5.0,2.5,-0.5]);
``` 
The function gives me 0.890896422653356 while I was [expecting](https://www.wolframalpha.com/input?i=roots+of+x%5E5-2.5x%5E4%2B5.0x%5E3-5.0x%5E2%2B2.5x-0.5) 0.5.

Also, in [src/numerical/eigen.rs](https://github.com/vorot/roots/blob/3caf9740f66aa213468136dea7a59d04a33cc0a7/src/numerical/eigen.rs#L715C5-L730C6) there is a test with fake value to pass. 
```
let roots = dbg!(find_roots_eigen(vec![
            -3.75f64 / -14.0625f64,
            29.75f64 / -14.0625f64,
            4.0f64 / -14.0625f64,
            -16.0f64 / -14.0625f64,
        ]));

// (According to Wolfram Alpha, roots must be -1.1016116464173349f64, 0.9682783130840016f64)
// This means that this function cannot handle such small discriminant.
// But at least it finds the right number of them.
assert_eq!(roots[0], 0.9990584398692597f64);
assert_eq!(roots[1], 0.12511486301943303f64);
```
If you know it does not work, why not throw an error or something? Maybe there is a need to rework the algorithm?

**Comment by vorot** [comment]
Any improvements are welcome.
