### ISSUE TITLE
`test_find_roots_eigen_tim_lueke`  fails on Debian i386 (really i686)

### ISSUE THREAD

**Issue by mr-c** [vorot/roots#33]
Hello, I recently packaged the `roots` crate for Debian, as it is a pre-requisite for https://github.com/sourmash-bio/sourmash/

We have a single test failing on our 32-bit x86 architecture:

```
---- numerical::eigen::test::test_find_roots_eigen_tim_lueke stdout ----
[src/numerical/eigen.rs:719:21] find_roots_eigen(vec![-3.75f64 / -14.0625f64, 29.75f64 / -14.0625f64, 4.0f64 /
-14.0625f64, -16.0f64 / -14.0625f64,]) = [
    0.9990584398692588,
    0.12511486301943328,
]
thread 'numerical::eigen::test::test_find_roots_eigen_tim_lueke' panicked at src/numerical/eigen.rs:728:9:
assertion `left == right` failed
  left: 0.9990584398692588
 right: 0.9990584398692597
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.81.0/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.81.0/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.81.0/library/core/src/panicking.rs:365:5
   4: roots::numerical::eigen::test::test_find_roots_eigen_tim_lueke
             at /usr/share/cargo/registry/roots-0.0.8/src/numerical/eigen.rs:728:9
   5: roots::numerical::eigen::test::test_find_roots_eigen_tim_lueke::{{closure}}
             at /usr/share/cargo/registry/roots-0.0.8/src/numerical/eigen.rs:716:41
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.81.0/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.81.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

[(The full log)](https://buildd.debian.org/status/fetch.php?pkg=rust-roots&arch=i386&ver=0.0.8-1&stamp=1729062704&raw=0)

Otherwise all the other tests passed, and on all of our other supported architectures all tests passed: https://buildd.debian.org/status/package.php?p=rust%2droots (the top part of the the table are the supported, official Debian architectures)

If this crate is note designed nor tested for 32-bit architectures, as is common for scientific and mathematical computing software in this decade, we can happily exclude 32-bit architectures from testing. Just let me know

**Comment by vorot** [comment]
If would be much more desired to replace `assert_eq!(...)` with `assert_float_eq!(1e-14f64, ...)` instead of disabling tests.
