### ISSUE TITLE
Very small values of `a` produce incorrect results in `find_roots_cubic`

### ISSUE THREAD

**Issue by Logicalshift** [vorot/roots#6]
Hi, it looks like when presented with very small values for `a` - that is, for curves that are almost but note quite quadratic - `find_roots_cubic` produces wildly incorrect results. The following test case illustrates the issue:

```
    use roots::*;

    let a = -0.000000000000000040410628481035;
    let b = 0.0126298310280606;
    let c = -0.100896606408756;
    let d = 0.0689539597036461;

    let x = 0.754710877053; // Expected root

    assert!((a*x*x*x + b*x*x + c*x + d).abs() < 0.001);

    let roots = find_roots_cubic(a, b, c, d);
    let roots = match roots {
        Roots::No(_)    => vec![],
        Roots::One(r)   => r.to_vec(),
        Roots::Two(r)   => r.to_vec(),
        Roots::Three(r) => r.to_vec(),
        Roots::Four(r)  => r.to_vec()
    };

    println!("{:?}", roots);
    assert!(roots.into_iter().any(|r| (r-x).abs() < 0.01));
```

For me, this outputs `[312537357195212.44]` as the result and fails the assertion. There appears to be a threshold around `a=-0.0000000002` where the results become correct again. 

I've been working around this by treating small values of `a` as indicating that the curve is quadratic, which works for my use case (solving for points on bezier curves, which are quite commonly very close to being quadratic) but I'm not sure is good enough for a general solution where the other coefficients might also have very small values.

**Comment by vorot** [comment]
Thank you for reporting. According to https://www.wolframalpha.com/input/?i=-0.000000000000000040410628481035*x%5E3%2B0.0126298310280606*x%5E2-0.100896606408756*x%2B0.0689539597036461
this equation has 3 roots: 0.7547108770537, 7.23404258961, and 312537357195213 
There must something wrong in the code path when the discriminant is so low (~1e-6). I am going to investigate that.

**Comment by vorot** [comment]
The precision of calculation arccos was not enough to produce valid results. The trigonometric solution is now only used for normalized cubic equations. For unnormalized equations, the general formula (using complex numbers) seems to produce better results.

The change is pushed to master. The timeline of updating crates.io is not yet defined.
